apiVersion: v2
name: allure-server
description: Allure Server application helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 2.9.1
dependencies:
- name: postgresql
  version: 11.0.8
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
