{{- if .Values.ingress.enabled }}

  {{- $servicePort := .Values.service.name -}}
  {{- $serviceName := "allure-server-service" -}}
  {{- $ingressExtraPaths := .Values.ingress.extraPaths -}}

---

{{- $apiV1 := true -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
{{- $apiV1 = false -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: allure-server-ingress
  annotations:
  {{ toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
  {{- if .Values.ingress.labels }}
  {{ toYaml .Values.ingress.labels | indent 4 }}
  {{- end }}
  {{- include "allure-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
        {{- range $ingressExtraPaths }}
        - path: {{ default "/" .path | quote }}
          {{- if $apiV1 }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ default $serviceName .service }}
              port:
                name: {{ default $servicePort .port }}
          {{- else }}
          backend:
            serviceName: {{ default $serviceName .service }}
            servicePort: {{ default $servicePort .port }}
          {{- end }}
        {{- end }}
        - path: {{ default "/" .path | quote }}
          {{- if $apiV1 }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ default $serviceName .service }}
              port:
                name: {{ default $servicePort .port }}
          {{- else }}
          backend:
            serviceName: {{ default $serviceName .service }}
            servicePort: {{ default $servicePort .port }}
          {{- end }}
  {{- end }}

  {{- end -}}